spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/dockerdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: dockeruser
    password: dockerpassword
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  doc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
  cache:
    type: redis

  redis:
    host: localhost
    port: 6379
server:
  port: 8080
